---
title: "Turns & Positions"
format: 
  html:
    self-contained: true
    toc: true
output-file: "./output/03-turnspositions.html"
---

Script #03 for the project: "Relationship between tactical decisions and power demands during cycling in a male elite sprint triathlon world championship"

### Setup

### Read data

```{r}
d <- read.csv("../data/temp/cleaned-combined.csv")
```

### Identify turns

```{r}
# create data.frame with additional data on turns
turns <- data.frame(
  racetime = c(634,724,763,801,871,965,1005,1044,1115,1204,1243,1282,1355,1443,1485,1524,1592,1681,1723,1761,1831,1921,1961,1999),
  type = factor(rep.int(c("u","c"),12)),
  id = seq.int(to = 24),
  turn_id = rep.int(1:4,6),
  lap = rep(1:6, each = 4)
)
turns
```

### Plot turns

```{r}
# function to create a plot for the power data around a given race time
plot_turn <- function(time) {
  sprintarea <- data.frame(xmin = time, xmax = time+10, ymin = 0, ymax = 1000)
  p <- ggplot(d, aes(x = racetime, y = power, colour = athlete)) +
    geom_point(size = 2) +
    geom_line() +
    geom_rect(
      inherit.aes = FALSE, 
      data = sprintarea, 
      aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax), 
      alpha = 0.1) +
    scale_x_continuous(limits = c(time-10, time+20)) +
    theme_minimal()
  ggsave(
    filename = paste0("../plots/temp/turns/",time,".png"), 
    plot = p,
    dpi = 300, 
    width = 8, 
    height = 5,
    bg = "white")
}

# generate plots for each turn
purrr::walk(turns$racetime, plot_turn)
```

